---
- name: Backup management IP configuration
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: 'show interface management'
  register: management_ip_backup

- name: Reset configuration to factory defaults
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: 'request system private-data-reset'

- name: "Restore management IP configuration"
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: 'set deviceconfig system ip-address {{ management_ip_backup.stdout_lines[0].split()[2] }}'
  tags: reset2
...